### ISSUE TITLE
GeoLiteCity.dat not being downloaded

### ISSUE THREAD

**Issue by isisis** [snapshotpl/ZfSnapGeoip#10]
The file is not being downloaded by composer.
Even "php public/index.php geoip download" does not create the file.
Do you have an idea what's wrong here?

**Comment by snapshotpl** [comment]
@isisis do you have permission to write file?

**Comment by z133808** [comment]
@snapshotpl
thanks for you work  its run fine
if you had a little time. could you ISP implement to this project? 
https://www.maxmind.com/de/geoip2-isp-database

Mega thanks in advance
